"""Initial migration

Revision ID: 36c3b8a7c333
Revises: 
Create Date: 2025-02-13 10:36:43.385585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c3b8a7c333'
down_revision = None
branch_labels = None
depends_on = None


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('steps', mysql.TEXT(), nullable=True),
    sa.Column('is_vegetarian', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_gluten_free', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_nut_free', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('recipe_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index('idx_dietary_flags', ['is_vegetarian', 'is_gluten_free', 'is_nut_free'], unique=False)

    
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_vegetarian', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_nut_free', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_gluten_free', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('ingredient',
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('containsNuts', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('containsGluten', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('containsMeat', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('reviews',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_text', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`rating` between 1 and 5)', name='reviews_chk_1'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name='reviews_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='reviews_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('pantry_ingredient',
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name='pantry_ingredient_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='pantry_ingredient_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingredient_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_favorite_recipes',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name='user_favorite_recipes_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_favorite_recipes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name='recipe_ingredient_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name='recipe_ingredient_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
